# NumPy Array Broadcasting

It allows to perform arithmetic operations on arrays of different shapes without reshaping them.

In [1]:
import numpy as np
array_2d=np.array([[2,3,],[3,4]])
scalar=3
result= array_2d + scalar
print(result)

[[5 6]
 [6 7]]


In [3]:
#broadcasting 1D to 2D array

array_1d=np.array([3,2])
array_2d=np.array([[2,3,],[3,4]])
result= array_1d + array_2d
print(result)

[[5 5]
 [6 6]]


#Normalizing Image Data

Normalizing means to center data by subtracting the mean ensuring features have zero mean, then scaling data by dividing standrad deviation.

Improves numerical stability and performance of algorithms like gradient descent.

In [8]:
image=np.array([[100, 120, 130],
               [90, 110, 140],
               [90, 110, 140]])

mean=image.mean(axis=0)
std=image.std(axis=0)
normalized_image=(image-mean)/std
print(normalized_image)

[[ 1.41421356  1.41421356 -1.41421356]
 [-0.70710678 -0.70710678  0.70710678]
 [-0.70710678 -0.70710678  0.70710678]]


# Centering Data in Machine Learning

In [10]:
data=np.array([[100, 120, 130],
               [90, 110, 140]])

mean=data.mean(axis=0)
centered_data=(image-mean)
print(centered_data)

[[ 5.  5. -5.]
 [-5. -5.  5.]
 [-5. -5.  5.]]


#NumPy Arithmetic operations

In [12]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([11,22,33,44,55,66,77])

add_ans=np.add(a,b)
sub_ans=np.subtract(b,a)
div_ans=np.divide(a,b)
mul_ans=np.multiply(a,b)
pow_ans=np.power(b,a)

print(add_ans)
print(sub_ans)
print(div_ans)
print(mul_ans)
print(pow_ans)

[12 24 36 48 60 72 84]
[10 20 30 40 50 60 70]
[0.09090909 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909
 0.09090909]
[ 11  44  99 176 275 396 539]
[            11            484          35937        3748096
      503284375    82653950016 16048523266853]


# Aggregation functions

sum,mean,min,max

In [18]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([11,22,33,44,55,66,77])
res=np.sum(a)
print(res)
min_res=np.minimum(a,b)
print(min_res)
max_res=np.maximum(a,b)
print(max_res)

28
[1 2 3 4 5 6 7]
[11 22 33 44 55 66 77]
