# NumPy

NumPy( short for Numerical Python) one of the most fundamental libraries in Python for scientific computing which provides support for large multi-dimensional arrays and matrices along with a collectin of mathematical functions to operate on arrays.

In [ ]:
import numpy as np

tup=(1,2,3,4)
numpy_array=np.array(tup)
print(numpy_array)

[1 2 3 4]


In [ ]:
zeros=np.zeros((1,2))
ones=np.ones((1,2))
constants=np.full((1,2),7)
range=np.arange(0,9,2) # start stop step
linspace=np.linspace(0,1,4) # start stop num

print("zeros array:","\n",zeros)
print("Ones Array:","\n",ones)
print("Constant Array:","\n",constants)
print("Range Array:","\n",range)
print("Linspace Array:","\n",linspace)

zeros array: 
 [[0. 0.]]
Ones Array: 
 [[1. 1.]]
Constant Array: 
 [[7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.         0.33333333 0.66666667 1.        ]


In [ ]:
random=np.random.rand(2,6)
normal=np.random.randn(1,5)
randint=np.random.randint(3,9,size=(3,3))
print(random)
print(normal)
print(randint)

[[0.90215454 0.05600133 0.73791332 0.23161213 0.78830234 0.71269967]
 [0.26097366 0.32139754 0.47480577 0.97542981 0.0593892  0.77616151]]
[[ 0.28048837 -0.03506681  1.80252718  1.81446469 -1.40942221]]
[[6 5 7]
 [6 8 5]
 [8 7 8]]


In [ ]:
identity_mat=np.eye(3)
diagonal_arr=np.diag([1,2])
zeros_like=np.zeros_like(diagonal_arr)
ones_like=np.ones_like(identity_mat)

print("identity matrix:\n ",identity_mat)
print("diagonal array:\n ",diagonal_arr)
print("zeros like array:\n ",zeros_like)
print("ones like array:\n ",ones_like)

identity matrix:
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
diagonal array:
  [[1 0]
 [0 2]]
zeros like array:
  [[0 0]
 [0 0]]
ones like array:
  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Numpy Array Indexing**

Array indexing in NumPy means accessing specific elements or subsets of data within an array.

In [ ]:
#accessing elements in 1D array
arr=np.array([10,20,30,40])
print(arr[2])

30


In [ ]:
#accessing elements in multidmensional arrays

#2D array
matrix=np.array([[1,2],[2,2],[3,4]])
print(matrix)
print(matrix[1,0])

#3D array
matrix1=np.array([[[1,2,3],[2,5,2],[3,2,4]]])
print(matrix1)
print(matrix1[0,0,1])

[[1 2]
 [2 2]
 [3 4]]
2
[[[1 2 3]
  [2 5 2]
  [3 2 4]]]
2


In [ ]:
# slicing array
arr=np.array([10,20,30,40])
print(arr[0:3])

[10 20 30]


In [ ]:
#boolean indexing
arr=np.array([3,6,9,12])
print(arr[arr<=9])
print(arr[(arr<=6) & (arr< 12)])

[3 6 9]
[3 6]


In [ ]:
# modifying array elements
arr=np.array([3,6,9,12])
arr[0:2]=4
print(arr)

[ 4  4  9 12]


In [ ]:
# fancy indexing
arr=np.array([3,6,9,12])
indices=[1,2,3]
print(arr[indices])

[ 6  9 12]
