# Products of Vectors and Matrices in NumPy

**Inner Product of Vectors and matrices**

Inner product or dot product is the sum .got by multiplying matching elements of two arrays and then adding them.

syntax:

numpy.inner(arr1,arr2)

In [2]:
import numpy as np

a=np.array([2,3])
b=np.array([4,5])
print(np.inner(a,b))

x=np.array([[2,3,4],[3,4,5]])
y=np.array([[1,5,0],[2,3,4]])
print(np.inner(x,y))


23
[[17 29]
 [23 38]]


# Outer Product of Vectors and Matrices

Outer Product of vectors creates a matrix each element is the product of elements from both vectors.

syntax:

numpy.outer(arr1,arr2,out=None)


In [3]:
import numpy as np

a=np.array([2,3])
b=np.array([4,5])
print(np.outer(a,b))

x=np.array([[2,3,4],[3,4,5]])
y=np.array([[1,5,0],[2,3,4]])
print(np.outer(x,y))

[[ 8 10]
 [12 15]]
[[ 2 10  0  4  6  8]
 [ 3 15  0  6  9 12]
 [ 4 20  0  8 12 16]
 [ 3 15  0  6  9 12]
 [ 4 20  0  8 12 16]
 [ 5 25  0 10 15 20]]


**Determinant of matrix**



In [5]:
#using numpy.linalg.slotdet() for large matrices

A=np.array([[25,10],[30,44]])
sign,logdet=np.linalg.slogdet(A)
res=sign*np.exp(logdet)
print(res)

800.0000000000006


In [7]:
#using numpy.linalg.det()

A=np.array([[1,2],[2,1]])
res=np.linalg.det(A)
print(res)

-2.9999999999999996


**Inverse matrix**

The inverse of a matrix is that matrix which when multiplied with original matrix will give aan identity matrix.

It only exists when matrix is non-singular.

Syntax:

numpy.linalg.inv(a)

In [8]:
A=np.array([[2,4,8],
           [3,5,8],
           [6,8,9]])
res=np.linalg.inv(A)
print(res)

[[  9.5 -14.    4. ]
 [-10.5  15.   -4. ]
 [  3.   -4.    1. ]]
