In [ ]:
import numpy as np

arr=np.array([[[1,2],[2,3],[3,4],[4,5]]])
print("Given Array: ",arr)
res_arr=arr[:,[0,1]]
print("Accessed array: \n",res_arr)

Given Array:  [[[1 2]
  [2 3]
  [3 4]
  [4 5]]]
Accessed array: 
 [[[1 2]
  [2 3]]]


In [ ]:
import numpy as np

arr=np.array([[1,2],[2,3],[3,4],[4,5]])
print("Given Array: ",arr)
res_arr=arr[[0,1]]
print("Accessed array: \n",res_arr)

Given Array:  [[1 2]
 [2 3]
 [3 4]
 [4 5]]
Accessed array: 
 [[1 2]
 [2 3]]


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([3,2,1])

#stacking 2 1-d arrays row-wise
stac=np.stack((a,b),axis=0)
print(stac)

[[1 2 3]
 [3 2 1]]


In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([3,2,1])

#stacking 2 1-d arrays column-wise
stac=np.stack((a,b),axis=1)
print(stac)

[[1 3]
 [2 2]
 [3 1]]


In [4]:
import numpy as np
a=np.array([1,2,3])
b=np.array([3,2,1])

#stacking 2 1-d arrays along -1 axis
stac=np.stack((a,b),axis=-1)
print(stac)

[[1 3]
 [2 2]
 [3 1]]


Note: -1 means 'last dimension wise while 2 axis are possible(0 and 1) so -1 is same as 1.