# Sparse Matrices in NumPy


If most of the elemnets of matrix have 0 value, it is called sparse matrix.Two major benefits:

*Storage

*Computing time

Syntax:

for compressed sparse row format:
scipy.sparse.csr_matrix(shape=None,dtype=None)

for compressed sparse column format:
scipy.sparse.csc_matrix(shape=None,dtype=None)

In [ ]:
#create sparse matrix using csr_matrix()

import numpy as np
from scipy.sparse import csr_matrix

# creating an empty 3*4 sparse matrix
sparseMat= csr_matrix((3,4),dtype=np.int8).toarray()
print(sparseMat)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
#create sparse matrix using csr_matrix()

from scipy.sparse import csr_matrix

row=np.array([0,0,1,2,2,1,0])
column=np.array([0,2,1,0,0,0,1])

#taking data
data=np.array([1,2,3,4,5,6,7])

#creating sparse_matrix
sparsemat=csr_matrix((data,(row,column)),shape=(3,3)).toarray()

print(sparsemat)

[[1 7 2]
 [6 3 0]
 [9 0 0]]


In [ ]:
#create sparse matrix using csc_matrix()

from scipy.sparse import csc_matrix

#creating empty sparse matrix
sparse_matrix=csc_matrix((3,4),dtype=np.int8).toarray()
print(sparse_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
#creating sprase matrix using csc_matrix()

from scipy.sparse import csc_matrix
row=np.array([1,2,1,0,0,0,0])
col=np.array([0,0,0,1,2,1,0])

#taking data
data=np.array([1,2,4,6,8,9,3])

#creating sparse matrix
sparseMat=csc_matrix((data,(row,col)),shape=(3,3)).toarray()

print(sparseMat)

[[ 3 15  8]
 [ 5  0  0]
 [ 2  0  0]]
