#PyTorch

It is an open-source deep learning framework designed to simplify the process of building neural netwroks and machine learning models.

In [ ]:
! pip install torch torchvision

In [8]:
import torch

tensor_1d=torch.tensor([1,2,3])
print("1D Tensor (Vector):")
print(tensor_1d)

tensor_2d=torch.tensor([[1,2,3],[3,4,5]])
print("1D Tensor (Vector):")
print(tensor_1d)
print()

random_tensor=torch.rand(2,3)
print("Random Tensor(2*3):")
print(random_tensor)

zeros_tensor=torch.zeros(2,3)
print("Zeros Tensor (2*3):")
print(zeros_tensor)

ones_tensor=torch.ones(2,3)
print("Ones Tensor(3*3):")
print(ones_tensor)

1D Tensor (Vector):
tensor([1, 2, 3])
1D Tensor (Vector):
tensor([1, 2, 3])

Random Tensor(2*3):
tensor([[0.6988, 0.1567, 0.0654],
        [0.0535, 0.7375, 0.4494]])
Zeros Tensor (2*3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor(3*3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Tensor Operations in PyTorch: Indexing,Slicing,Reshaping.

In [14]:
import torch

tensor=torch.tensor([[1,2],[3,4],[5,6]])

element=tensor[1,0]
print(f"indexed element (Row1, Column0): {element}")

slice_tensor=tensor[:2,:]
print(f"Sliced tensor ( First two rows all elements): \n {slice_tensor}")

reshaped_tensor=tensor.view(2,3)
print(f"Reshaped Tensor (2*3): \n {reshaped_tensor}")

indexed element (Row1, Column0): 3
Sliced tensor ( First two rows all elements): 
 tensor([[1, 2],
        [3, 4]])
Reshaped Tensor (2*3): 
 tensor([[1, 2, 3],
        [4, 5, 6]])


Common Tensor Functions: Broadcasting Matrix, Multiplication etc.

In [16]:
import torch

tensor_a=torch.tensor([[1,2,3],[4,8,10]])
tensor_b=torch.tensor([6,12,24])

broadcasted_result=tensor_a + tensor_b
print(f"Broadcasted Addition result:\n {broadcasted_result}")

matrix_mul_result=torch.matmul(tensor_a , tensor_b)
print(f"matrix multplication result: {matrix_mul_result}")

Broadcasted Addition result:
 tensor([[ 7, 14, 27],
        [10, 20, 34]])
matrix multplication result: tensor([102, 360])
